# The URL the site will be built for
base_url = "https://hpc.uit.no"

title = "High-performance computing group at UiT"

description = '''
When your computation does not fit anymore into your computer, we are the group
to talk to.
'''

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false


[markdown]

highlight_code = true
highlight_theme = "cheerfully-light"


[extra]

navigation = [
  { name = "Home", target = "/" },
  { name = "About us", target = "/about/" },
  { name = "Projects", target = "/projects/" },
  { name = "Training and events", target = "/training/" },
  { name = "Getting started", target = "/accounts/" },
  { name = "Newsletter/blog", target = "/blog/" },
  { name = "Contact", target = "/contact/" },
]

logo_uit_seal_white = "img/UiT_seal_white.png"
logo_uit_seal_black = "img/UiT_seal_black.png"
logo_uit_seal_blue  = "img/UiT_seal_blue.png"

logo_uit_2line_white = "img/UiT_2line_white.png"
logo_uit_2line_blue  = "img/UiT_2line_blue.png"

logo_nris_acronym = "img/NRIS_acronym.jpg"

# twitter_image = "example.png"
